//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc_StokTakip.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Satislar
    {
        public int s_Id { get; set; }
        public string s_Adi { get; set; }
        public Nullable<int> u_Id { get; set; }
        public Nullable<int> m_Id { get; set; }
        public Nullable<int> s_Fiyat { get; set; }
        public Nullable<int> s_Adet { get; set; }
    
        public virtual Musteriler Musteriler { get; set; }
        public virtual Urunler Urunler { get; set; }
    }
}
